[Loupe] Format fields with underscore
schranz-search/schranz-search pull request #372
Opened 2024-03-05 10:46 UTC by ker0x

2024-03-08 15:19 UTC, alexander-schranz requested changes
Looks good, I need to check if we can maybe with the current test fixtures create a reproducable failing test case. But I think at current state the `memory` adapter is very minimal doesn't supported already this kind of nested properties.

2024-03-08 15:19 UTC, alexander-schranz commented on packages/seal-loupe-adapter/src/LoupeHelper.php
> +    public function formatField(string $field): string
We should mark this method as `@internal`

```suggestion
    /**
     * @internal
     */
    public function formatField(string $field): string
```

2024-03-08 15:19 UTC, alexander-schranz commented on integrations/spiral/src/Console/IndexCreateCommand.php
> +    private ?string $engineName = null;
The code style was updated. Please rebase to 0.3

2024-03-08 16:40 UTC, ker0x commented
@alexander-schranz i'va rebase and apply your suggestions 😉

2024-03-20 23:29 UTC, merged

2024-03-20 23:29 UTC, alexander-schranz commented
@ker0x thank you!